services:
  postgres:
    image: postgres:15
    container_name: pageform_postgres
    environment:
      POSTGRES_DB: pageform_db
      POSTGRES_USER: pageform_user
      POSTGRES_PASSWORD: pageform_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: